add update latest release

diff --git a/.github/workflow_templates/deploy-channel.multi.yml b/.github/workflow_templates/deploy-channel.multi.yml
--- a/.github/workflow_templates/deploy-channel.multi.yml
+++ b/.github/workflow_templates/deploy-channel.multi.yml
@@ -136,9 +136,11 @@ Jobs for visual control allowed editions when approving deploy to environments.
       - name: Run deploy stub
         run: exit 0
 
-  prepare_channel_releases:
-    name: Prepare channel releases
+  post_deploy_preparation:
+    name: Post deploy preparation
     runs-on: [self-hosted, regular]
+    outputs:
+      STABLE_VERSION: ${{ steps.collect-channel-versions.outputs.stable_version }}    
     needs:
       - run_deploy
     steps:
@@ -170,7 +172,8 @@ Jobs for visual control allowed editions when approving deploy to environments.
           {{ $.Files.Get "channels.yaml" | indent 4 }}
           EOF
 
-      - name: Generate channel releases config map
+      - name: Collect channel versions
+        id: collect-channel-versions
         run: python .github/scripts/python/generate-channel-releases-cm.py
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -208,7 +211,7 @@ stage:
     name: "{!{ $env_properties.job_name }!}"
     runs-on: [self-hosted, regular]
     needs:
-      - prepare_channel_releases
+      - post_deploy_preparation
     env:
       WERF_CHANNEL: "ea"
     steps:
@@ -245,6 +248,62 @@ stage:
           WERF_DIR: "publish-channels"
           WERF_DEV: "true"
 
-{!{ end -}!}
+{!{ end }!}
+  update_latest_release:
+    name: Update latest release
+    runs-on: ubuntu-latest
+    needs: post_deploy_preparation
+    permissions:
+      contents: write
 
+    steps:
+      - name: Make latest stable release
+        env:
+          STABLE_VERSION: ${{ needs.post_deploy_preparation.outputs.STABLE_VERSION }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          set -e
+
+          url="https://api.github.com"
+
+          owner="${GITHUB_REPOSITORY%/*}"
+          repo="${GITHUB_REPOSITORY#*/}"
+
+          release_by_tag="${url}/repos/${GITHUB_REPOSITORY}/releases/tags/${STABLE_VERSION}"
+
+          echo "${owner}"
+          echo "${repo}"
+          # echo $release_by_tag
+          response=$(curl -s -w "\n%{http_code}" -X GET ${release_by_tag} \
+              -H "Authorization: Bearer ${GITHUB_TOKEN}") || exit $?
+
+          response_code=$(echo "$response" | tail -n1)
+
+          if [[ $response_code != '200' ]]; then
+              echo -e "\e[31mERROR: Unable to determinate release id by tag!\e[0m"
+              echo -e "\e[31mURL: ${release_by_tag}!\e[0m"
+              echo -e "\e[31mResponse code: ${response_code}!\e[0m"
+              exit 1
+          fi
+
+          release_id=$(echo "$response" | sed  '$d' | jq ".id")
+          release_name=$(echo "$response" | sed  '$d' | jq ".name")
+          echo $release_id
+
+          update_release="${url}/repos/${GITHUB_REPOSITORY}/releases/${release_id}"
+
+          response=$(curl -s -w "\n%{http_code}" -X PATCH ${update_release} \
+              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
+              -d '{"prerelease":false,"make_latest":true}') || exit $?
+
+          response_code=$(echo "$response" | tail -n1)
+
+          if [[ $response_code != '200' ]]; then
+              echo -e "\e[31mERROR: Unable to update release ${release_name}!\e[0m"
+              echo -e "\e[31mURL: ${update_release}!\e[0m"
+              echo -e "\e[31mResponse code: ${response_code}!\e[0m"
+              exit 1
+          fi
+
+          echo -e "\e[32mRelease ${release_name} has been successfully marked as latest."
 {!{ end -}!}
