chore: Add block e2e tests during dev image build
Signed-off-by: Alexey Paschenko <alexey.paschenko@flant.com>

diff --git a/.github/workflows/e2e-azure.yml b/.github/workflows/e2e-azure.yml
--- a/.github/workflows/e2e-azure.yml
+++ b/.github/workflows/e2e-azure.yml
@@ -327,6 +327,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -419,6 +420,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -830,6 +858,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -922,6 +951,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -1333,6 +1389,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -1425,6 +1482,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -1836,6 +1920,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -1928,6 +2013,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -2339,6 +2451,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -2431,6 +2544,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -2842,6 +2982,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -2934,6 +3075,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -3345,6 +3513,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -3437,6 +3606,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
diff --git a/.github/workflows/e2e-daily.yml b/.github/workflows/e2e-daily.yml
--- a/.github/workflows/e2e-daily.yml
+++ b/.github/workflows/e2e-daily.yml
@@ -240,6 +240,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -332,6 +333,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -702,6 +730,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -798,6 +827,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -1209,6 +1265,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -1301,6 +1358,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -1679,6 +1763,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -1771,6 +1856,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -2137,6 +2249,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -2229,6 +2342,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -2603,6 +2743,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -2695,6 +2836,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -3061,6 +3229,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -3153,6 +3322,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -3523,6 +3719,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -3615,6 +3812,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -3997,6 +4221,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -4089,6 +4314,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
diff --git a/.github/workflows/e2e-eks.yml b/.github/workflows/e2e-eks.yml
--- a/.github/workflows/e2e-eks.yml
+++ b/.github/workflows/e2e-eks.yml
@@ -327,6 +327,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -423,6 +424,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -867,6 +895,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -963,6 +992,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -1407,6 +1463,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -1503,6 +1560,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -1947,6 +2031,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -2043,6 +2128,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -2487,6 +2599,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -2583,6 +2696,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -3027,6 +3167,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -3123,6 +3264,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -3567,6 +3735,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -3663,6 +3832,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
diff --git a/.github/workflows/e2e-vsphere.yml b/.github/workflows/e2e-vsphere.yml
--- a/.github/workflows/e2e-vsphere.yml
+++ b/.github/workflows/e2e-vsphere.yml
@@ -327,6 +327,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -419,6 +420,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -822,6 +850,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -914,6 +943,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -1317,6 +1373,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -1409,6 +1466,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -1812,6 +1896,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -1904,6 +1989,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -2307,6 +2419,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -2399,6 +2512,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -2802,6 +2942,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -2894,6 +3035,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -3297,6 +3465,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -3389,6 +3558,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
diff --git a/.github/workflows/e2e-yandex-cloud.yml b/.github/workflows/e2e-yandex-cloud.yml
--- a/.github/workflows/e2e-yandex-cloud.yml
+++ b/.github/workflows/e2e-yandex-cloud.yml
@@ -327,6 +327,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -419,6 +420,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -826,6 +854,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -918,6 +947,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -1325,6 +1381,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -1417,6 +1474,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -1824,6 +1908,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -1916,6 +2001,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -2323,6 +2435,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -2415,6 +2528,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -2822,6 +2962,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -2914,6 +3055,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -3321,6 +3489,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -3413,6 +3582,33 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
