chore: Add block e2e tests during dev image build
Signed-off-by: Alexey Paschenko <alexey.paschenko@flant.com>

diff --git a/.github/workflows/e2e-daily.yml b/.github/workflows/e2e-daily.yml
--- a/.github/workflows/e2e-daily.yml
+++ b/.github/workflows/e2e-daily.yml
@@ -240,6 +240,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -332,6 +333,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -702,6 +731,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -798,6 +828,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -1209,6 +1267,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -1301,6 +1360,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -1679,6 +1766,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -1771,6 +1859,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -2137,6 +2253,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -2229,6 +2346,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -2603,6 +2748,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -2695,6 +2841,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -3061,6 +3235,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -3153,6 +3328,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -3523,6 +3726,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -3615,6 +3819,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -3997,6 +4229,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "false"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -4089,6 +4322,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
diff --git a/.github/workflows/e2e-vcd.yml b/.github/workflows/e2e-vcd.yml
--- a/.github/workflows/e2e-vcd.yml
+++ b/.github/workflows/e2e-vcd.yml
@@ -167,6 +167,104 @@ jobs:
 
   # </template: git_info_job>
 
+
+  # </template: block-e2e-until-image-is-not-ready>
+  block-e2e-until-image-is-not-ready:
+    name: Block e2e until the docker image is not ready
+    runs-on: ubuntu-latest
+    if: ${{ github.event.pull_request.user.login != 'deckhouse-BOaTswain' }}
+    steps:
+      - id: block-e2e
+        name: Block e2e until the docker image is not ready
+        uses: actions/github-script@v6.4.1
+        with:
+          script: |
+              const core = require('@actions/core');
+              const Octokit = require('@octokit/rest');
+
+              const WORKFLOW_NAME = 'Sleep job';
+              const WORKFLOW_STATUS_RUNNING = 'in_progress';
+              const WORKFLOW_STATUS_COMPLETED = 'completed';
+              const MAX_ATTEMPTS = 60;
+              const TIMEOUT_BETWEEN_ATTEMPT = 1000 * 30; // 10 секунд
+              const MAX_ITEMS_PER_PAGE = 100;
+
+              const token = process.env.GITHUB_TOKEN;
+              const repo = process.env.REPO;
+              const prName = context.payload.inputs.pull_request_ref;
+              const octokit = new Octokit({ auth: token });
+
+
+              /**
+              * @param {string} repo 
+              * @param {string} branch 
+              * @returns {Promise<boolean>}
+              */
+              async function isReadyToE2E(repo, branch) {
+                  try {
+                      const [owner, repoName] = repo.split('/');
+                      const { data } = await octokit.actions.listWorkflowRunsForRepo({
+                          owner,
+                          repo: repoName,
+                          branch: branch,
+                          per_page: MAX_ITEMS_PER_PAGE,
+                      });
+
+                      // Проверяем наличие активных workflow 'Sleep job'
+                          const activeRuns = data.workflow_runs.filter(run => 
+                          run.name === WORKFLOW_NAME && run.status === WORKFLOW_STATUS_RUNNING
+                      );
+
+                      if (activeRuns.length > 0) {
+                          console.log(`Есть активные джобы '${WORKFLOW_NAME}', ждём их завершения.`);
+                          return false;
+                      }
+
+                      console.log(`Активных джоб '${WORKFLOW_NAME}' не найдено, проверяем завершение первой джобы.`);
+                          // Проверка первой завершенной джобы 'Sleep job'
+                          const completedRun = data.workflow_runs.find(run => 
+                          run.name === WORKFLOW_NAME && run.status === WORKFLOW_STATUS_COMPLETED
+                      );
+
+                      if (completedRun) {
+                      if (completedRun.conclusion === 'success') {
+                          console.log('Первая джоба закончилась успешно.');
+                          return true;
+                      } else {
+                          console.error('Первая джоба закончилась с ошибкой.');
+                          core.setFailed('Актуального образа нет, первая джоба завершилась с ошибкой.');
+                          return false;
+                      }
+                      } else {
+                          console.error('Первая завершенная джоба не найдена.');
+                          core.setFailed('Не найдена завершенная джоба для анализа.');
+                          return false;
+                      }
+                  } catch (error) {
+                      core.setFailed(error.message);
+                      return false;
+                  }
+              }
+
+              function sleep(ms) {
+                  return new Promise(resolve => setTimeout(resolve, ms));
+              }
+
+              (async () => {
+                  for (let i = 0; i < MAX_ATTEMPTS; i++) {
+                      console.log(`Попытка ${i + 1} из ${MAX_ATTEMPTS}`);
+                      const isReady = await isReadyToE2E(repo, prName);
+                      if (isReady) {
+                      // добавить код для проверки образа, если джоба завершилась успешно.
+                      return;
+                      }
+                      await sleep(TIMEOUT_BETWEEN_ATTEMPT);
+                  }
+                  core.setFailed('Не удалось дождаться завершения джоб за допустимое количество попыток.');
+              })();
+
+  # </template: block-e2e-until-image-is-not-ready>
+
   # <template: check_e2e_labels_job>
   check_e2e_labels:
     name: Check e2e labels
@@ -327,6 +425,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -419,6 +518,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -834,6 +961,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -926,6 +1054,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -1341,6 +1497,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -1433,6 +1590,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -1848,6 +2033,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -1940,6 +2126,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -2355,6 +2569,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -2447,6 +2662,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -2862,6 +3105,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -2954,6 +3198,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
@@ -3369,6 +3641,7 @@ jobs:
           INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
           MANUAL_RUN: "true"
           MULTIMASTER: ${{ needs.check_e2e_labels.outputs.multimaster }}
+          WAIT_IMAGE_TIME: 1800 # 30 minutes
         run: |
           # Calculate unique prefix for e2e test.
           # GITHUB_RUN_ID is a unique number for each workflow run.
@@ -3461,6 +3734,34 @@ jobs:
             MASTERS_COUNT=1
           fi
           echo "Multimaster set ${MULTIMASTER}, MASTERS_COUNT set ${MASTERS_COUNT}"
+
+
+          echo "Starting a check to verify that the image exists in the registry."
+          start_time=$(date +%s)
+          while true; do
+              docker pull "${INSTALL_IMAGE_NAME}"
+              if [ $? -ne 0 ]; then
+                  echo "failed pull image"
+              else
+                  echo "success pull image"
+                  break
+              fi
+              sleep 5
+              current_time=$(date +%s)
+
+              # Calculating the time difference in seconds 
+              if [[ -n "${start_time}" && -n "${current_time}" ]]; then
+                  elapsed_seconds=$(( current_time - start_time ))
+              else
+                  echo "Error time calculating..."
+                  continue
+              fi
+
+              if (( $elapsed_seconds >= ${WAIT_IMAGE_TIME} )); then
+                  echo "${elapsed_seconds} seconds have passed; the check is complete."
+                  break
+              fi
+          done
 
           # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
           echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
