[ci] Add label for prevent destroy cluster after not passed e2e tests
Signed-off-by: Nikolay Mitrofanov <nikolay.mitrofanov@flant.com>

diff --git a/.github/workflows/e2e-daily.yml b/.github/workflows/e2e-daily.yml
--- a/.github/workflows/e2e-daily.yml
+++ b/.github/workflows/e2e-daily.yml
@@ -288,6 +288,7 @@ jobs:
           echo '::echo::off'
 
       - name: "Run e2e test: AWS/Containerd/1.21"
+        id: run-e2e-AWS-Containerd-1.21
         env:
           PROVIDER: AWS
           CRI: Containerd
@@ -337,11 +338,36 @@ jobs:
             -w /deckhouse \
           ${INSTALL_IMAGE_NAME} \
           bash /deckhouse/testing/cloud_layouts/script.sh run-test
+          exit_code=$?
 
+          ssh_string_file="${TMP_DIR_PATH}/ssh-master-connection-string"
+          if [ "$exit_code" != 0 && -f "$ssh_string_file" ]; then
+            ssh_string="$(cat $ssh_string_file)"
+            echo '::echo::on'
+            echo "::set-output name=ssh-master-connection-string::${ssh_string}"
+            echo '::echo::off'
+          fi
+
+          exit "$exit_code"
         # </template: e2e_run_template>
 
+      - name: Check stay failed cluster
+        if: ${{ failed() }}
+        id: check_stay_failed_cluster
+        uses: { !{ index (ds "actions") "actions/github-script" }! }
+        with:
+          # it sets `should_run` output var if e2e/stay-failed-cluster label
+          script: |
+            const ci = require('./.github/scripts/js/ci');
+            return await ci.checkLabel({
+              github,
+              context,
+              core,
+              labelType: 'e2e-stay-failed',
+            })
+
       - name: Cleanup bootstrapped cluster
-        if: always()
+        if: ${{ success() || !steps.check_stay_failed_cluster.should_run }}
         env:
           PROVIDER: AWS
           CRI: Containerd
@@ -391,8 +417,26 @@ jobs:
             -w /deckhouse \
           ${INSTALL_IMAGE_NAME} \
           bash /deckhouse/testing/cloud_layouts/script.sh cleanup
+          exit_code=$?
 
+          ssh_string_file="${TMP_DIR_PATH}/ssh-master-connection-string"
+          if [ "$exit_code" != 0 && -f "$ssh_string_file" ]; then
+            ssh_string="$(cat $ssh_string_file)"
+            echo '::echo::on'
+            echo "::set-output name=ssh-master-connection-string::${ssh_string}"
+            echo '::echo::off'
+          fi
+
+          exit "$exit_code"
         # </template: e2e_run_template>
+
+      - name: Save dhctl state
+        if: ${{ failed() && !steps.check_failed_cluster.should_run }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: failed_cluster_stateaws_containerd_1_21
+          path: |
+            ${{ steps.setup.outputs.tmp-dir-path}}/dhctl
 
       - name: Save test results
         if: always()
@@ -646,6 +690,7 @@ jobs:
           echo '::echo::off'
 
       - name: "Run e2e test: Azure/Containerd/1.21"
+        id: run-e2e-Azure-Containerd-1.21
         env:
           PROVIDER: Azure
           CRI: Containerd
@@ -699,11 +744,36 @@ jobs:
             -w /deckhouse \
           ${INSTALL_IMAGE_NAME} \
           bash /deckhouse/testing/cloud_layouts/script.sh run-test
+          exit_code=$?
 
+          ssh_string_file="${TMP_DIR_PATH}/ssh-master-connection-string"
+          if [ "$exit_code" != 0 && -f "$ssh_string_file" ]; then
+            ssh_string="$(cat $ssh_string_file)"
+            echo '::echo::on'
+            echo "::set-output name=ssh-master-connection-string::${ssh_string}"
+            echo '::echo::off'
+          fi
+
+          exit "$exit_code"
         # </template: e2e_run_template>
 
+      - name: Check stay failed cluster
+        if: ${{ failed() }}
+        id: check_stay_failed_cluster
+        uses: { !{ index (ds "actions") "actions/github-script" }! }
+        with:
+          # it sets `should_run` output var if e2e/stay-failed-cluster label
+          script: |
+            const ci = require('./.github/scripts/js/ci');
+            return await ci.checkLabel({
+              github,
+              context,
+              core,
+              labelType: 'e2e-stay-failed',
+            })
+
       - name: Cleanup bootstrapped cluster
-        if: always()
+        if: ${{ success() || !steps.check_stay_failed_cluster.should_run }}
         env:
           PROVIDER: Azure
           CRI: Containerd
@@ -757,8 +827,26 @@ jobs:
             -w /deckhouse \
           ${INSTALL_IMAGE_NAME} \
           bash /deckhouse/testing/cloud_layouts/script.sh cleanup
+          exit_code=$?
 
+          ssh_string_file="${TMP_DIR_PATH}/ssh-master-connection-string"
+          if [ "$exit_code" != 0 && -f "$ssh_string_file" ]; then
+            ssh_string="$(cat $ssh_string_file)"
+            echo '::echo::on'
+            echo "::set-output name=ssh-master-connection-string::${ssh_string}"
+            echo '::echo::off'
+          fi
+
+          exit "$exit_code"
         # </template: e2e_run_template>
+
+      - name: Save dhctl state
+        if: ${{ failed() && !steps.check_failed_cluster.should_run }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: failed_cluster_stateazure_containerd_1_21
+          path: |
+            ${{ steps.setup.outputs.tmp-dir-path}}/dhctl
 
       - name: Save test results
         if: always()
@@ -1012,6 +1100,7 @@ jobs:
           echo '::echo::off'
 
       - name: "Run e2e test: GCP/Containerd/1.21"
+        id: run-e2e-GCP-Containerd-1.21
         env:
           PROVIDER: GCP
           CRI: Containerd
@@ -1059,11 +1148,36 @@ jobs:
             -w /deckhouse \
           ${INSTALL_IMAGE_NAME} \
           bash /deckhouse/testing/cloud_layouts/script.sh run-test
+          exit_code=$?
 
+          ssh_string_file="${TMP_DIR_PATH}/ssh-master-connection-string"
+          if [ "$exit_code" != 0 && -f "$ssh_string_file" ]; then
+            ssh_string="$(cat $ssh_string_file)"
+            echo '::echo::on'
+            echo "::set-output name=ssh-master-connection-string::${ssh_string}"
+            echo '::echo::off'
+          fi
+
+          exit "$exit_code"
         # </template: e2e_run_template>
 
+      - name: Check stay failed cluster
+        if: ${{ failed() }}
+        id: check_stay_failed_cluster
+        uses: { !{ index (ds "actions") "actions/github-script" }! }
+        with:
+          # it sets `should_run` output var if e2e/stay-failed-cluster label
+          script: |
+            const ci = require('./.github/scripts/js/ci');
+            return await ci.checkLabel({
+              github,
+              context,
+              core,
+              labelType: 'e2e-stay-failed',
+            })
+
       - name: Cleanup bootstrapped cluster
-        if: always()
+        if: ${{ success() || !steps.check_stay_failed_cluster.should_run }}
         env:
           PROVIDER: GCP
           CRI: Containerd
@@ -1111,8 +1225,26 @@ jobs:
             -w /deckhouse \
           ${INSTALL_IMAGE_NAME} \
           bash /deckhouse/testing/cloud_layouts/script.sh cleanup
+          exit_code=$?
 
+          ssh_string_file="${TMP_DIR_PATH}/ssh-master-connection-string"
+          if [ "$exit_code" != 0 && -f "$ssh_string_file" ]; then
+            ssh_string="$(cat $ssh_string_file)"
+            echo '::echo::on'
+            echo "::set-output name=ssh-master-connection-string::${ssh_string}"
+            echo '::echo::off'
+          fi
+
+          exit "$exit_code"
         # </template: e2e_run_template>
+
+      - name: Save dhctl state
+        if: ${{ failed() && !steps.check_failed_cluster.should_run }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: failed_cluster_stategcp_containerd_1_21
+          path: |
+            ${{ steps.setup.outputs.tmp-dir-path}}/dhctl
 
       - name: Save test results
         if: always()
@@ -1366,6 +1498,7 @@ jobs:
           echo '::echo::off'
 
       - name: "Run e2e test: Yandex.Cloud/Containerd/1.21"
+        id: run-e2e-Yandex.Cloud-Containerd-1.21
         env:
           PROVIDER: Yandex.Cloud
           CRI: Containerd
@@ -1417,11 +1550,36 @@ jobs:
             -w /deckhouse \
           ${INSTALL_IMAGE_NAME} \
           bash /deckhouse/testing/cloud_layouts/script.sh run-test
+          exit_code=$?
 
+          ssh_string_file="${TMP_DIR_PATH}/ssh-master-connection-string"
+          if [ "$exit_code" != 0 && -f "$ssh_string_file" ]; then
+            ssh_string="$(cat $ssh_string_file)"
+            echo '::echo::on'
+            echo "::set-output name=ssh-master-connection-string::${ssh_string}"
+            echo '::echo::off'
+          fi
+
+          exit "$exit_code"
         # </template: e2e_run_template>
 
+      - name: Check stay failed cluster
+        if: ${{ failed() }}
+        id: check_stay_failed_cluster
+        uses: { !{ index (ds "actions") "actions/github-script" }! }
+        with:
+          # it sets `should_run` output var if e2e/stay-failed-cluster label
+          script: |
+            const ci = require('./.github/scripts/js/ci');
+            return await ci.checkLabel({
+              github,
+              context,
+              core,
+              labelType: 'e2e-stay-failed',
+            })
+
       - name: Cleanup bootstrapped cluster
-        if: always()
+        if: ${{ success() || !steps.check_stay_failed_cluster.should_run }}
         env:
           PROVIDER: Yandex.Cloud
           CRI: Containerd
@@ -1473,8 +1631,26 @@ jobs:
             -w /deckhouse \
           ${INSTALL_IMAGE_NAME} \
           bash /deckhouse/testing/cloud_layouts/script.sh cleanup
+          exit_code=$?
 
+          ssh_string_file="${TMP_DIR_PATH}/ssh-master-connection-string"
+          if [ "$exit_code" != 0 && -f "$ssh_string_file" ]; then
+            ssh_string="$(cat $ssh_string_file)"
+            echo '::echo::on'
+            echo "::set-output name=ssh-master-connection-string::${ssh_string}"
+            echo '::echo::off'
+          fi
+
+          exit "$exit_code"
         # </template: e2e_run_template>
+
+      - name: Save dhctl state
+        if: ${{ failed() && !steps.check_failed_cluster.should_run }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: failed_cluster_stateyandex-cloud_containerd_1_21
+          path: |
+            ${{ steps.setup.outputs.tmp-dir-path}}/dhctl
 
       - name: Save test results
         if: always()
@@ -1728,6 +1904,7 @@ jobs:
           echo '::echo::off'
 
       - name: "Run e2e test: OpenStack/Containerd/1.21"
+        id: run-e2e-OpenStack-Containerd-1.21
         env:
           PROVIDER: OpenStack
           CRI: Containerd
@@ -1775,11 +1952,36 @@ jobs:
             -w /deckhouse \
           ${INSTALL_IMAGE_NAME} \
           bash /deckhouse/testing/cloud_layouts/script.sh run-test
+          exit_code=$?
 
+          ssh_string_file="${TMP_DIR_PATH}/ssh-master-connection-string"
+          if [ "$exit_code" != 0 && -f "$ssh_string_file" ]; then
+            ssh_string="$(cat $ssh_string_file)"
+            echo '::echo::on'
+            echo "::set-output name=ssh-master-connection-string::${ssh_string}"
+            echo '::echo::off'
+          fi
+
+          exit "$exit_code"
         # </template: e2e_run_template>
 
+      - name: Check stay failed cluster
+        if: ${{ failed() }}
+        id: check_stay_failed_cluster
+        uses: { !{ index (ds "actions") "actions/github-script" }! }
+        with:
+          # it sets `should_run` output var if e2e/stay-failed-cluster label
+          script: |
+            const ci = require('./.github/scripts/js/ci');
+            return await ci.checkLabel({
+              github,
+              context,
+              core,
+              labelType: 'e2e-stay-failed',
+            })
+
       - name: Cleanup bootstrapped cluster
-        if: always()
+        if: ${{ success() || !steps.check_stay_failed_cluster.should_run }}
         env:
           PROVIDER: OpenStack
           CRI: Containerd
@@ -1827,8 +2029,26 @@ jobs:
             -w /deckhouse \
           ${INSTALL_IMAGE_NAME} \
           bash /deckhouse/testing/cloud_layouts/script.sh cleanup
+          exit_code=$?
 
+          ssh_string_file="${TMP_DIR_PATH}/ssh-master-connection-string"
+          if [ "$exit_code" != 0 && -f "$ssh_string_file" ]; then
+            ssh_string="$(cat $ssh_string_file)"
+            echo '::echo::on'
+            echo "::set-output name=ssh-master-connection-string::${ssh_string}"
+            echo '::echo::off'
+          fi
+
+          exit "$exit_code"
         # </template: e2e_run_template>
+
+      - name: Save dhctl state
+        if: ${{ failed() && !steps.check_failed_cluster.should_run }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: failed_cluster_stateopenstack_containerd_1_21
+          path: |
+            ${{ steps.setup.outputs.tmp-dir-path}}/dhctl
 
       - name: Save test results
         if: always()
@@ -2082,6 +2302,7 @@ jobs:
           echo '::echo::off'
 
       - name: "Run e2e test: vSphere/Containerd/1.21"
+        id: run-e2e-vSphere-Containerd-1.21
         env:
           PROVIDER: vSphere
           CRI: Containerd
@@ -2131,11 +2352,36 @@ jobs:
             -w /deckhouse \
           ${INSTALL_IMAGE_NAME} \
           bash /deckhouse/testing/cloud_layouts/script.sh run-test
+          exit_code=$?
 
+          ssh_string_file="${TMP_DIR_PATH}/ssh-master-connection-string"
+          if [ "$exit_code" != 0 && -f "$ssh_string_file" ]; then
+            ssh_string="$(cat $ssh_string_file)"
+            echo '::echo::on'
+            echo "::set-output name=ssh-master-connection-string::${ssh_string}"
+            echo '::echo::off'
+          fi
+
+          exit "$exit_code"
         # </template: e2e_run_template>
 
+      - name: Check stay failed cluster
+        if: ${{ failed() }}
+        id: check_stay_failed_cluster
+        uses: { !{ index (ds "actions") "actions/github-script" }! }
+        with:
+          # it sets `should_run` output var if e2e/stay-failed-cluster label
+          script: |
+            const ci = require('./.github/scripts/js/ci');
+            return await ci.checkLabel({
+              github,
+              context,
+              core,
+              labelType: 'e2e-stay-failed',
+            })
+
       - name: Cleanup bootstrapped cluster
-        if: always()
+        if: ${{ success() || !steps.check_stay_failed_cluster.should_run }}
         env:
           PROVIDER: vSphere
           CRI: Containerd
@@ -2185,8 +2431,26 @@ jobs:
             -w /deckhouse \
           ${INSTALL_IMAGE_NAME} \
           bash /deckhouse/testing/cloud_layouts/script.sh cleanup
+          exit_code=$?
 
+          ssh_string_file="${TMP_DIR_PATH}/ssh-master-connection-string"
+          if [ "$exit_code" != 0 && -f "$ssh_string_file" ]; then
+            ssh_string="$(cat $ssh_string_file)"
+            echo '::echo::on'
+            echo "::set-output name=ssh-master-connection-string::${ssh_string}"
+            echo '::echo::off'
+          fi
+
+          exit "$exit_code"
         # </template: e2e_run_template>
+
+      - name: Save dhctl state
+        if: ${{ failed() && !steps.check_failed_cluster.should_run }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: failed_cluster_statevsphere_containerd_1_21
+          path: |
+            ${{ steps.setup.outputs.tmp-dir-path}}/dhctl
 
       - name: Save test results
         if: always()
@@ -2440,6 +2704,7 @@ jobs:
           echo '::echo::off'
 
       - name: "Run e2e test: Static/Containerd/1.21"
+        id: run-e2e-Static-Containerd-1.21
         env:
           PROVIDER: Static
           CRI: Containerd
@@ -2487,11 +2752,36 @@ jobs:
             -w /deckhouse \
           ${INSTALL_IMAGE_NAME} \
           bash /deckhouse/testing/cloud_layouts/script.sh run-test
+          exit_code=$?
 
+          ssh_string_file="${TMP_DIR_PATH}/ssh-master-connection-string"
+          if [ "$exit_code" != 0 && -f "$ssh_string_file" ]; then
+            ssh_string="$(cat $ssh_string_file)"
+            echo '::echo::on'
+            echo "::set-output name=ssh-master-connection-string::${ssh_string}"
+            echo '::echo::off'
+          fi
+
+          exit "$exit_code"
         # </template: e2e_run_template>
 
+      - name: Check stay failed cluster
+        if: ${{ failed() }}
+        id: check_stay_failed_cluster
+        uses: { !{ index (ds "actions") "actions/github-script" }! }
+        with:
+          # it sets `should_run` output var if e2e/stay-failed-cluster label
+          script: |
+            const ci = require('./.github/scripts/js/ci');
+            return await ci.checkLabel({
+              github,
+              context,
+              core,
+              labelType: 'e2e-stay-failed',
+            })
+
       - name: Cleanup bootstrapped cluster
-        if: always()
+        if: ${{ success() || !steps.check_stay_failed_cluster.should_run }}
         env:
           PROVIDER: Static
           CRI: Containerd
@@ -2539,8 +2829,26 @@ jobs:
             -w /deckhouse \
           ${INSTALL_IMAGE_NAME} \
           bash /deckhouse/testing/cloud_layouts/script.sh cleanup
+          exit_code=$?
 
+          ssh_string_file="${TMP_DIR_PATH}/ssh-master-connection-string"
+          if [ "$exit_code" != 0 && -f "$ssh_string_file" ]; then
+            ssh_string="$(cat $ssh_string_file)"
+            echo '::echo::on'
+            echo "::set-output name=ssh-master-connection-string::${ssh_string}"
+            echo '::echo::off'
+          fi
+
+          exit "$exit_code"
         # </template: e2e_run_template>
+
+      - name: Save dhctl state
+        if: ${{ failed() && !steps.check_failed_cluster.should_run }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: failed_cluster_statestatic_containerd_1_21
+          path: |
+            ${{ steps.setup.outputs.tmp-dir-path}}/dhctl
 
       - name: Save test results
         if: always()
